config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :posts, only: %i[new create index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: { minimum: 3 }
  validates :body, presence: true, length: { maximum: 150 }
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  before_save :downcase_email
  before_create :create_remember_digest

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  has_secure_password
  has_many :posts

  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?

    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  private

  def downcase_email
    email.downcase!
  end

  def create_remember_digest
    self.remember_token = User.new_token
    self.remember_digest = User.digest(remember_token)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in_user, only: %i[new create]

  def index
    @posts = Post.all.order(:user_id)
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = 'New post created!'
      redirect_to posts_path
    else
      flash.now[:danger] = "Title/body can't be empty!"
      render 'new'
    end
  end

  private

  def post_params
    params.require(:posts).permit(:title, :body)
  end

  def logged_in_user
    return if logged_in?

    flash[:danger] = 'Please login'
    redirect_to login_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:sessions][:email].downcase)
    if user&.authenticate(params[:sessions][:password])
      log_in user
      remember user
      redirect_to posts_path
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to posts_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)

    if @user.save
      flash[:success] = "User successfully created."
      log_in @user
      redirect_to posts_path
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:users).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def logged_in?
    !current_user.nil?
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: session[:user_id])
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user&.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def current_user=(user)
    @current_user = user
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container-fluid">
    <nav class="member" >
      <%= link_to "Members Only", root_path, class: "logo" %>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to 'Posts', posts_path %></li>
        <% if logged_in? %>
          <li><%= link_to 'Create post', new_post_path %></li>
          <li><%= link_to 'Log out', logout_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Sign in', login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class = "spacing"> </div>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_post.html.erb
<li>
  <h3><%= post.title %></h3>
  <p><%= post.body %></p>
  <% if logged_in? %>
    <p>Posted by: <%= post.user.name %></p>
  <% end %>
</li>

app/views/posts/index.html.erb
<%provide(:title, "Posts")%>

<h1 class = "post-heading">Posts</h1>

<ul class = "post-list">
  <%= render @posts %>
</ul>

app/views/posts/new.html.erb
<%provide(:title, "Create post")%>

<div class="form-wrap">
  <h1 class="h1-heading"> Create post </h1>

  <%=form_for(:posts, url:  posts_path, html: { class: 'form-style' } ) do |f| %>
    <%=f.label :title, class: 'form-label' %> <br>
    <%= f.text_field :title, class: 'form-input' %> <br>

    <%= f.label :body, class: 'form-label' %> <br>
    <%= f.text_area :body, class: 'form-input' %> <br>

    <%= f.submit "Create post", class: 'form-btn' %>
    
  <% end %>
</div>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<div class="center jumbotron">
  <h1>Welcome to the Members Only App</h1>
  <%= link_to "Sign up now!", signup_path, class: "login-btn btn btn-lg btn-primary" %>
</div>

app/views/users/new.html.erb
<%provide(:title, "Sign up")%>
<div class="form-wrap">
  <h1 class="h1-heading" > Sign up </h1>

  <%=form_for(:users, url: signup_path, html: { class: 'form-style' } ) do |f| %>
    <%= f.label :name, class: 'form-label' %> <br>
    <%= f.text_field :name, class: 'form-input' %> <br>

    <%= f.label :email, class: 'form-label' %> <br>
    <%= f.email_field :email, class: 'form-input' %> <br>

    <%= f.label :password, class: 'form-label' %> <br>
    <%= f.password_field :password, class: 'form-input' %> <br>

    <%= f.label :password_confirmation, class: 'form-label' %> <br>
    <%= f.password_field :password_confirmation, class: 'form-input' %> <br>

    <%= f.submit "Sign up", class: 'form-btn'%>
    
  <% end %>
</div>